### ISSUE TITLE
run sample but got error

### ISSUE THREAD

**Issue by yongchengmiao** [Smat26/pyLogicFlowChart#1]
I execute the sample code, but there is an error problem.
`
[root@ flowchart]# python3 analyzer.py -s sample.py -v interesting_variable -a list-append
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/graphviz/backend.py", line 164, in run
    proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "analyzer.py", line 120, in <module>
    analyzer.report()
  File "analyzer.py", line 89, in report
    self.graph.view()
  File "/usr/lib/python3.6/site-packages/graphviz/files.py", line 242, in view
    quiet=quiet, quiet_view=quiet_view)
  File "/usr/lib/python3.6/site-packages/graphviz/files.py", line 209, in render
    quiet=quiet)
  File "/usr/lib/python3.6/site-packages/graphviz/backend.py", line 221, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/usr/lib/python3.6/site-packages/graphviz/backend.py", line 167, in run
    raise ExecutableNotFound(cmd)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'flowchart.gv'], make sure the Graphviz executables are on your systems' PATH
`

**Comment by Smat26** [comment]
This is old, but make sure you have GraphViz on your system
